// Trade presets: seed job types, terminology and accent color for a new business.
// Add a trade by adding an entry here — no other code changes needed.

const STATUSES = [
  { key: 'new',       label: 'New',       color: '#7c3aed' },
  { key: 'visit',     label: 'Visit',     color: '#0891b2' },
  { key: 'quoted',    label: 'Quoted',    color: '#b45309' },
  { key: 'accepted',  label: 'Accepted',  color: '#db2777' },
  { key: 'scheduled', label: 'Scheduled', color: '#1d4ed8' },
  { key: 'done',      label: 'Done',      color: '#15803d' },
  { key: 'paid',      label: 'Paid',      color: '#475569' },
];

const CLIENT_TERMS   = { client: 'Client',   clients: 'Clients',   job: 'Job', jobs: 'Jobs' };
const CUSTOMER_TERMS = { client: 'Customer', clients: 'Customers', job: 'Job', jobs: 'Jobs' };

export const PRESETS = {
  fence: {
    accent: '#92400e',
    terms: CLIENT_TERMS,
    statuses: STATUSES,
    taxBps: 825, // sample: 8.25% (typical Brazos County TX). Owners set their own.
    catalog: [
      ['6 ft cedar privacy fence', 'ft', 32, 'Fence Installation'],
      ['4 ft cedar picket fence', 'ft', 24, 'Fence Installation'],
      ['Chain-link fence, 4 ft', 'ft', 18, 'Fence Installation'],
      ['Pipe and 3-rail (horse fence)', 'ft', 26, 'Fence Installation'],
      ['Walk gate', 'each', 285, 'Fence Installation'],
      ['Double drive gate', 'each', 650, 'Fence Installation'],
      ['Old fence tear-out and haul-off', 'ft', 4, 'Fence Installation'],
      ['Upgrade to steel posts', 'each', 45, 'Fence Installation'],
      ['Replace fence picket', 'each', 12, 'Repair'],
      ['Replace post, set in concrete', 'each', 95, 'Repair'],
      ['Gate repair or re-hang', 'each', 85, 'Repair'],
      ['Panel section repair', 'each', 110, 'Repair'],
      ['Service call', 'job', 125, 'Repair'],
      ['Power wash and prep', 'ft', 1.25, 'Staining & Sealing'],
      ['Stain and seal, one side', 'ft', 4.5, 'Staining & Sealing'],
      ['Second coat', 'ft', 1.5, 'Staining & Sealing'],
      ['Deck stain and seal', 'sq ft', 2.75, 'Staining & Sealing'],
      ['Permit or HOA fee', 'each', 75, null, 'fee'],
      ['Hard digging (rock or roots)', '%', 10, 'Fence Installation', 'surcharge'],
      ['Repeat customer discount', 'each', 100, null, 'discount'],
    ],
    jobTypes: ['Fence Installation', 'Repair', 'Staining & Sealing'],
  },
  roofing: {
    accent: '#b91c1c',
    terms: CUSTOMER_TERMS,
    statuses: STATUSES,
    taxBps: 825,
    catalog: [
      ['Architectural shingles, installed', 'sq', 475, 'Roof Replacement'],
      ['Tear-off and disposal', 'sq', 95, 'Roof Replacement'],
      ['Underlayment and ice/water shield', 'sq', 60, 'Roof Replacement'],
      ['Flashing and vents', 'job', 350, 'Roof Replacement'],
      ['Shingle repair', 'job', 250, 'Roof Repair'],
      ['Leak diagnosis', 'job', 150, 'Roof Repair'],
      ['Roof inspection and report', 'job', 175, 'Inspection'],
      ['Seamless gutters', 'ft', 9, 'Gutters'],
      ['Downspout', 'each', 45, 'Gutters'],
      ['Steep roof (8/12 or more)', '%', 15, 'Roof Replacement', 'surcharge'],
      ['Permit fee', 'each', 150, null, 'fee'],
      ['Dumpster', 'each', 550, 'Roof Replacement', 'fee'],
      ['Decking replacement, if needed', 'sheet', 85, 'Roof Replacement'],
    ],
    depositPct: 30,
    jobTypes: ['Roof Replacement', 'Roof Repair', 'Inspection', 'Gutters'],
  },
  lawn: {
    accent: '#166534',
    terms: CUSTOMER_TERMS,
    statuses: STATUSES,
    taxBps: 825,
    catalog: [
      ['Mowing visit', 'visit', 45, 'Mowing'],
      ['Edging and trimming', 'visit', 15, 'Mowing'],
      ['Cleanup, leaves and debris', 'job', 200, 'Cleanup'],
      ['Mulch, installed', 'yd', 85, 'Mulching'],
      ['Sprinkler head replacement', 'each', 22, 'Irrigation Repair'],
      ['Irrigation service call', 'job', 95, 'Irrigation Repair'],
    ],
    usesVisits: false,
    depositPct: 0,
    minChargeDollars: 45,
    jobTypes: ['Mowing', 'Cleanup', 'Mulching', 'Irrigation Repair'],
  },
  'pressure-washing': {
    accent: '#0369a1',
    terms: CUSTOMER_TERMS,
    statuses: STATUSES,
    taxBps: 825,
    catalog: [
      ['House wash', 'sq ft', 0.25, 'House Wash'],
      ['Driveway and concrete wash', 'sq ft', 0.2, 'Driveway & Concrete'],
      ['Deck wash', 'sq ft', 0.35, 'Deck & Fence'],
      ['Fence wash', 'ft', 1.5, 'Deck & Fence'],
      ['Roof soft wash', 'sq ft', 0.4, 'Roof Wash'],
      ['Second story surcharge', '%', 15, 'House Wash', 'surcharge'],
    ],
    usesVisits: false,
    depositPct: 0,
    minChargeDollars: 150,
    jobTypes: ['House Wash', 'Driveway & Concrete', 'Deck & Fence', 'Roof Wash'],
  },
};


// Sample prices below are ballpark starting points. Every owner sets their own under "Prices and settings".
// Catalog rows: [name, unit, dollars, job type (or null), kind?]  kind = item | labor | allowance | fee | discount | surcharge.
// For a surcharge, "dollars" is the percent (10 = 10%).
const TRADES = {
  plumbing: {
    accent: '#0e7490', terms: CUSTOMER_TERMS, taxBps: 825, usesVisits: false, depositPct: 0, minChargeDollars: 89,
    jobTypes: ['Repair', 'Water Heater', 'Drain Cleaning', 'Fixture Install', 'Repipe or Remodel'],
    catalog: [
      ['Service call and diagnosis', 'job', 89, 'Repair', 'fee'],
      ['Labor', 'hr', 125, null, 'labor'],
      ['Water heater, 40 gal, installed', 'each', 1450, 'Water Heater'],
      ['Tankless water heater, installed', 'each', 3400, 'Water Heater'],
      ['Toilet, replaced', 'each', 325, 'Fixture Install'],
      ['Faucet, installed', 'each', 185, 'Fixture Install'],
      ['Garbage disposal, replaced', 'each', 285, 'Fixture Install'],
      ['Drain clearing, main line', 'job', 275, 'Drain Cleaning'],
      ['Camera inspection', 'job', 225, 'Drain Cleaning'],
      ['Shutoff or hose bib valve', 'each', 165, 'Repair'],
      ['Water line repair', 'job', 350, 'Repair'],
      ['Permit fee', 'each', 75, null, 'fee'],
      ['Haul away old fixture', 'each', 40, null, 'fee'],
      ['After hours or weekend', '%', 50, null, 'surcharge'],
    ],
  },
  electrical: {
    accent: '#a16207', terms: CUSTOMER_TERMS, taxBps: 825, usesVisits: false, depositPct: 0, minChargeDollars: 95,
    jobTypes: ['Repair', 'Install', 'Panel and Service', 'EV Charger'],
    catalog: [
      ['Service call and diagnosis', 'job', 95, 'Repair', 'fee'],
      ['Labor', 'hr', 110, null, 'labor'],
      ['Outlet, installed', 'each', 145, 'Install'],
      ['GFCI outlet, installed', 'each', 165, 'Install'],
      ['Ceiling fan, installed', 'each', 225, 'Install'],
      ['Recessed light, installed', 'each', 175, 'Install'],
      ['Panel upgrade, 200 amp', 'job', 2800, 'Panel and Service'],
      ['Whole-house surge protector', 'each', 450, 'Panel and Service'],
      ['EV charger, installed', 'each', 950, 'EV Charger'],
      ['Permit fee', 'each', 85, null, 'fee'],
      ['After hours or weekend', '%', 50, null, 'surcharge'],
    ],
  },
  hvac: {
    accent: '#1d4ed8', terms: CUSTOMER_TERMS, taxBps: 825, usesVisits: true, depositPct: 30, minChargeDollars: 89,
    jobTypes: ['Repair', 'Maintenance', 'System Replacement', 'New Install'],
    catalog: [
      ['Diagnostic fee', 'job', 89, 'Repair', 'fee'],
      ['Labor', 'hr', 120, null, 'labor'],
      ['Capacitor replaced', 'each', 285, 'Repair'],
      ['Refrigerant', 'lb', 85, 'Repair'],
      ['AC or furnace tune-up', 'visit', 129, 'Maintenance'],
      ['Duct cleaning', 'job', 425, 'Maintenance'],
      ['Replacement system, standard efficiency', 'each', 6200, 'System Replacement'],
      ['Replacement system, high efficiency', 'each', 8400, 'System Replacement'],
      ['Replacement system, premium', 'each', 11200, 'System Replacement'],
      ['Smart thermostat, installed', 'each', 285, null],
      ['Permit fee', 'each', 150, null, 'fee'],
      ['After hours or weekend', '%', 50, null, 'surcharge'],
    ],
  },
  painting: {
    accent: '#7c3aed', terms: CLIENT_TERMS, taxBps: 825, usesVisits: true, depositPct: 30, minChargeDollars: 250,
    jobTypes: ['Interior', 'Exterior', 'Cabinets', 'Touch-up'],
    catalog: [
      ['Interior walls, two coats', 'sq ft', 2.25, 'Interior'],
      ['Ceilings', 'sq ft', 1.25, 'Interior'],
      ['Trim and baseboards', 'ft', 1.75, 'Interior'],
      ['Exterior repaint', 'sq ft', 2.75, 'Exterior'],
      ['Power wash and prep', 'sq ft', 0.35, 'Exterior'],
      ['Cabinet doors, sprayed', 'each', 95, 'Cabinets'],
      ['Drywall patch and repair', 'each', 85, null],
      ['Paint and materials', 'job', 400, null, 'allowance'],
      ['Crew labor', 'day', 640, null, 'labor'],
      ['Lead-safe or high-ceiling work', '%', 10, null, 'surcharge'],
    ],
  },
  'junk-removal': {
    accent: '#15803d', terms: CUSTOMER_TERMS, taxBps: 825, usesVisits: false, depositPct: 0, minChargeDollars: 99,
    jobTypes: ['Household Junk', 'Construction Debris', 'Yard Waste', 'Estate Cleanout'],
    catalog: [
      ['Truck load (use 0.25, 0.5, 0.75 or 1 for part of a truck)', 'load', 450, null],
      ['Labor', 'hr', 60, null, 'labor'],
      ['Mattress or box spring', 'each', 35, null, 'fee'],
      ['Appliance with refrigerant', 'each', 60, null, 'fee'],
      ['Tires', 'each', 15, null, 'fee'],
      ['Heavy item (piano, safe, hot tub)', 'each', 100, null, 'fee'],
      ['Dump or disposal fee', 'ton', 65, null, 'fee'],
      ['Stairs or long carry', '%', 15, null, 'surcharge'],
      ['Same-day service', '%', 10, null, 'surcharge'],
    ],
  },
  'land-clearing': {
    accent: '#78350f', terms: CLIENT_TERMS, taxBps: 0, usesVisits: true, depositPct: 30, minChargeDollars: 500,
    jobTypes: ['Brush Clearing', 'Forestry Mulching', 'Lot Prep', 'Stump and Tree'],
    catalog: [
      ['Brush clearing', 'acre', 1800, 'Brush Clearing'],
      ['Forestry mulching', 'acre', 2400, 'Forestry Mulching'],
      ['Lot clearing and grading', 'acre', 3200, 'Lot Prep'],
      ['Tree removal, small', 'each', 350, 'Stump and Tree'],
      ['Stump grinding', 'in', 4, 'Stump and Tree'],
      ['Skid steer with operator', 'hr', 145, null, 'labor'],
      ['Excavator or dozer with operator', 'hr', 165, null, 'labor'],
      ['Dump truck load, hauled off', 'load', 200, null],
      ['Debris burn or haul', 'job', 350, null],
      ['Mobilization', 'job', 350, null, 'fee'],
      ['Permit fee', 'each', 100, null, 'fee'],
    ],
  },
  'tree-service': {
    accent: '#166534', terms: CUSTOMER_TERMS, taxBps: 0, usesVisits: true, depositPct: 0, minChargeDollars: 200,
    jobTypes: ['Tree Removal', 'Trimming', 'Stump Grinding', 'Emergency'],
    catalog: [
      ['Tree removal, small', 'each', 450, 'Tree Removal'],
      ['Tree removal, medium', 'each', 950, 'Tree Removal'],
      ['Tree removal, large', 'each', 1800, 'Tree Removal'],
      ['Tree trimming', 'each', 275, 'Trimming'],
      ['Stump grinding', 'in', 4, 'Stump Grinding'],
      ['Crane', 'hr', 350, null, 'labor'],
      ['Cleanup and haul-off', 'job', 200, null],
      ['Storm or emergency', '%', 50, 'Emergency', 'surcharge'],
    ],
  },
  handyman: {
    accent: '#c2410c', terms: CUSTOMER_TERMS, taxBps: 825, usesVisits: false, depositPct: 0, minChargeDollars: 95,
    jobTypes: ['Repairs', 'Installs', 'Assembly', 'Punch List'],
    catalog: [
      ['Labor', 'hr', 75, null, 'labor'],
      ['Half day', 'job', 300, null, 'labor'],
      ['TV mounted', 'each', 150, 'Installs'],
      ['Interior door hung', 'each', 175, 'Installs'],
      ['Drywall patch', 'each', 95, 'Repairs'],
      ['Caulk and seal', 'job', 85, 'Repairs'],
      ['Furniture assembly', 'each', 60, 'Assembly'],
      ['Materials', 'job', 100, null, 'allowance'],
      ['Trip charge', 'job', 45, null, 'fee'],
    ],
  },
  concrete: {
    accent: '#475569', terms: CLIENT_TERMS, taxBps: 825, usesVisits: true, depositPct: 30, minChargeDollars: 800,
    jobTypes: ['Driveway', 'Patio', 'Foundation and Footings', 'Repair'],
    catalog: [
      ['Concrete flatwork, 4 in', 'sq ft', 8, 'Driveway'],
      ['Stamped or colored concrete', 'sq ft', 14, 'Patio'],
      ['Demo and haul old concrete', 'sq ft', 3, null],
      ['Gravel base prep', 'sq ft', 1.5, null],
      ['Rebar or wire mesh', 'sq ft', 0.75, null],
      ['Footing, formed and poured', 'ft', 45, 'Foundation and Footings'],
      ['Saw cuts and control joints', 'ft', 3, null],
      ['Pump truck', 'job', 450, null, 'fee'],
      ['Permit fee', 'each', 100, null, 'fee'],
    ],
  },
  'general-contractor': {
    accent: '#334155', terms: CLIENT_TERMS, taxBps: 825, usesVisits: true, depositPct: 30, minChargeDollars: 0,
    jobTypes: ['Remodel', 'Addition', 'Repair', 'Kitchen and Bath'],
    catalog: [
      ['Demolition', 'sq ft', 3, null],
      ['Framing', 'sq ft', 12, 'Addition'],
      ['Drywall hung and finished', 'sq ft', 3.5, null],
      ['Flooring, installed', 'sq ft', 6.5, null],
      ['Cabinets', 'job', 5000, 'Kitchen and Bath', 'allowance'],
      ['Countertops', 'job', 3500, 'Kitchen and Bath', 'allowance'],
      ['Crew labor', 'day', 640, null, 'labor'],
      ['Dumpster', 'each', 550, null, 'fee'],
      ['Permit fee', 'each', 250, null, 'fee'],
      ['Contingency for surprises', '%', 10, null, 'surcharge'],
    ],
  },
  'pest-control': {
    accent: '#be123c', terms: CUSTOMER_TERMS, taxBps: 825, usesVisits: false, depositPct: 0, minChargeDollars: 95,
    jobTypes: ['General Pest', 'Termite', 'Rodent', 'Mosquito'],
    catalog: [
      ['Initial treatment', 'job', 175, 'General Pest'],
      ['Quarterly service visit', 'visit', 125, 'General Pest'],
      ['Termite inspection', 'job', 95, 'Termite'],
      ['Termite treatment', 'ft', 12, 'Termite'],
      ['Rodent exclusion', 'hr', 85, 'Rodent', 'labor'],
      ['Mosquito treatment', 'visit', 85, 'Mosquito'],
      ['Bed bug treatment, per room', 'each', 450, null],
    ],
  },
};
for (const [k, t] of Object.entries(TRADES)) PRESETS[k] = { statuses: STATUSES, ...t };

export function getPreset(name) {
  const p = PRESETS[name];
  if (!p) throw new Error(`Unknown preset "${name}". Available: ${Object.keys(PRESETS).join(', ')}`);
  return p;
}
